name: Deploy to Firebase Hosting manually
on: workflow-dispatch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
        env:
            REACT_APP_API_URL: '${{ secrets.API_URL }}'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAMEBATTLE_EEF0D }}'
          channelId: live
          projectId: gamebattle-eef0d
